import { Injectable, BadRequestException, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../database/prisma.service';
import { SettingsHistoryService } from './settings-history.service';

/**
 * Service pour la gestion des années scolaires
 */
@Injectable()
export class AcademicYearSettingsService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly historyService: SettingsHistoryService,
  ) {}

  /**
   * Récupère toutes les années scolaires d'un tenant
   */
  async getAll(tenantId: string) {
    return this.prisma.academicYear.findMany({
      where: { tenantId },
      orderBy: { startDate: 'desc' },
      include: {
        _count: {
          select: {
            students: true,
            classes: true,
            grades: true,
          },
        },
      },
    });
  }

  /**
   * Récupère l'année scolaire active
   */
  async getActive(tenantId: string) {
    return this.prisma.academicYear.findFirst({
      where: { tenantId, isActive: true },
    });
  }

  /**
   * Récupère une année scolaire par ID
   */
  async getById(tenantId: string, id: string) {
    const year = await this.prisma.academicYear.findFirst({
      where: { tenantId, id },
      include: {
        _count: {
          select: {
            students: true,
            classes: true,
            grades: true,
            payments: true,
          },
        },
      },
    });

    if (!year) {
      throw new NotFoundException('Année scolaire non trouvée.');
    }

    return year;
  }

  /**
   * Crée une nouvelle année scolaire
   */
  async create(
    tenantId: string,
    data: {
      name: string;
      label: string;
      preEntryDate?: Date;
      startDate: Date;
      endDate: Date;
      isAutoGenerated?: boolean;
    },
    userId: string,
  ) {
    // Vérifier les chevauchements de dates
    const overlapping = await this.prisma.academicYear.findFirst({
      where: {
        tenantId,
        OR: [
          {
            startDate: { lte: data.endDate },
            endDate: { gte: data.startDate },
          },
        ],
      },
    });

    if (overlapping) {
      throw new BadRequestException(
        `Les dates chevauchent l'année scolaire "${overlapping.name}".`,
      );
    }

    const year = await this.prisma.academicYear.create({
      data: {
        tenantId,
        ...data,
        isActive: false,
      },
    });

    await this.historyService.logSettingChange(
      tenantId,
      null,
      'academic_year',
      'academic_year',
      { created: { old: null, new: year.name } },
      userId,
    );

    return year;
  }

  /**
   * Met à jour une année scolaire
   */
  async update(
    tenantId: string,
    id: string,
    data: {
      name?: string;
      label?: string;
      preEntryDate?: Date;
      startDate?: Date;
      endDate?: Date;
    },
    userId: string,
  ) {
    const existing = await this.getById(tenantId, id);

    // Vérifier si des données critiques existent avant modification des dates
    if ((data.startDate || data.endDate) && (existing._count.grades > 0 || existing._count.payments > 0)) {
      throw new BadRequestException(
        'Impossible de modifier les dates : des données existent (notes ou paiements).',
      );
    }

    const changes: Record<string, { old: any; new: any }> = {};
    Object.keys(data).forEach((key) => {
      if (data[key] !== undefined && existing[key] !== data[key]) {
        changes[key] = { old: existing[key], new: data[key] };
      }
    });

    if (Object.keys(changes).length === 0) {
      return existing;
    }

    const updated = await this.prisma.academicYear.update({
      where: { id },
      data: {
        ...data,
        updatedAt: new Date(),
      },
    });

    await this.historyService.logSettingChange(
      tenantId,
      null,
      'academic_year',
      'academic_year',
      changes,
      userId,
    );

    return updated;
  }

  /**
   * Active une année scolaire (désactive les autres)
   */
  async activate(tenantId: string, id: string, userId: string) {
    const year = await this.getById(tenantId, id);

    if (year.isActive) {
      return year;
    }

    // Transaction pour désactiver les autres et activer celle-ci
    await this.prisma.$transaction([
      this.prisma.academicYear.updateMany({
        where: { tenantId, isActive: true },
        data: { isActive: false },
      }),
      this.prisma.academicYear.update({
        where: { id },
        data: { isActive: true },
      }),
    ]);

    await this.historyService.logSettingChange(
      tenantId,
      null,
      'academic_year',
      'academic_year',
      { activated: { old: false, new: true, yearName: year.name } },
      userId,
    );

    return this.getById(tenantId, id);
  }

  /**
   * Verrouille une année scolaire (empêche les modifications)
   * Note: Le verrouillage est représenté par le fait qu'il y a des données
   * et que l'année n'est plus active
   */
  async lock(tenantId: string, id: string, userId: string) {
    const year = await this.getById(tenantId, id);

    if (year.isActive) {
      throw new BadRequestException(
        'Impossible de verrouiller l\'année active. Activez une autre année d\'abord.',
      );
    }

    await this.historyService.logSettingChange(
      tenantId,
      null,
      'academic_year',
      'academic_year',
      { locked: { old: false, new: true, yearName: year.name } },
      userId,
    );

    return { success: true, message: `Année ${year.name} verrouillée.` };
  }

  /**
   * Duplique les paramètres d'une année vers une nouvelle
   */
  async duplicate(
    tenantId: string,
    sourceId: string,
    data: {
      name: string;
      label: string;
      startDate: Date;
      endDate: Date;
      preEntryDate?: Date;
      duplicateClasses?: boolean;
      duplicateFees?: boolean;
      duplicateSubjects?: boolean;
    },
    userId: string,
  ) {
    const source = await this.getById(tenantId, sourceId);

    // Créer la nouvelle année
    const newYear = await this.create(
      tenantId,
      {
        name: data.name,
        label: data.label,
        startDate: data.startDate,
        endDate: data.endDate,
        preEntryDate: data.preEntryDate,
        isAutoGenerated: false,
      },
      userId,
    );

    // Dupliquer les classes si demandé
    if (data.duplicateClasses) {
      const classes = await this.prisma.class.findMany({
        where: { tenantId, academicYearId: sourceId },
      });

      for (const cls of classes) {
        await this.prisma.class.create({
          data: {
            tenantId,
            academicYearId: newYear.id,
            schoolLevelId: cls.schoolLevelId,
            name: cls.name,
            code: cls.code,
            capacity: cls.capacity,
          },
        });
      }
    }

    // Dupliquer les frais si demandé
    if (data.duplicateFees) {
      const feeDefinitions = await this.prisma.feeDefinition.findMany({
        where: { tenantId, academicYearId: sourceId },
      });

      for (const fee of feeDefinitions) {
        await this.prisma.feeDefinition.create({
          data: {
            tenantId,
            academicYearId: newYear.id,
            schoolLevelId: fee.schoolLevelId,
            name: fee.name,
            code: fee.code,
            amount: fee.amount,
            currency: fee.currency,
            dueDate: fee.dueDate,
            isRequired: fee.isRequired,
          },
        });
      }
    }

    await this.historyService.logSettingChange(
      tenantId,
      null,
      'academic_year',
      'academic_year',
      {
        duplicated: {
          old: null,
          new: newYear.name,
          sourceYear: source.name,
          options: {
            duplicateClasses: data.duplicateClasses,
            duplicateFees: data.duplicateFees,
            duplicateSubjects: data.duplicateSubjects,
          },
        },
      },
      userId,
    );

    return newYear;
  }

  /**
   * Supprime une année scolaire (si aucune donnée)
   */
  async delete(tenantId: string, id: string, userId: string) {
    const year = await this.getById(tenantId, id);

    if (year.isActive) {
      throw new BadRequestException('Impossible de supprimer l\'année active.');
    }

    const hasData =
      year._count.students > 0 ||
      year._count.classes > 0 ||
      year._count.grades > 0 ||
      year._count.payments > 0;

    if (hasData) {
      throw new BadRequestException(
        'Impossible de supprimer cette année : des données existent. ' +
        'Veuillez d\'abord supprimer ou archiver les données associées.',
      );
    }

    await this.prisma.academicYear.delete({ where: { id } });

    await this.historyService.logSettingChange(
      tenantId,
      null,
      'academic_year',
      'academic_year',
      { deleted: { old: year.name, new: null } },
      userId,
    );

    return { success: true, message: `Année ${year.name} supprimée.` };
  }

  /**
   * Génère automatiquement la prochaine année scolaire
   */
  async generateNext(tenantId: string, userId: string) {
    const currentYear = await this.getActive(tenantId);

    if (!currentYear) {
      throw new BadRequestException('Aucune année active. Créez d\'abord une année scolaire.');
    }

    // Calculer les dates de la nouvelle année
    const nextStartDate = new Date(currentYear.endDate);
    nextStartDate.setMonth(nextStartDate.getMonth() + 2); // ~2 mois après la fin
    nextStartDate.setDate(1); // Premier du mois (septembre)

    const nextEndDate = new Date(nextStartDate);
    nextEndDate.setMonth(nextEndDate.getMonth() + 10); // ~10 mois plus tard (juillet)

    // Générer le nom (ex: 2025-2026)
    const startYear = nextStartDate.getFullYear();
    const endYear = nextEndDate.getFullYear();
    const name = `${startYear}-${endYear}`;

    return this.create(
      tenantId,
      {
        name,
        label: `Année scolaire ${name}`,
        startDate: nextStartDate,
        endDate: nextEndDate,
        isAutoGenerated: true,
      },
      userId,
    );
  }
}
