'use client';

import {
  LayoutDashboard,
  Layers,
  BookOpen,
  Users,
  ClipboardList,
  Calendar,
  FileText,
  ShieldCheck,
  BarChart3,
  Package,
  Book,
  CalendarDays,
  NotebookPen,
  Sparkles,
} from 'lucide-react';

export const PEDAGOGY_SUBMODULE_TABS = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    path: '/app/pedagogy',
    icon: LayoutDashboard,
    roles: ['SUPER_DIRECTOR', 'PLATFORM_OWNER', 'SCHOOL_OWNER', 'SCHOOL_ADMIN', 'director', 'admin', 'TEACHER', 'TEACHER_RESP'],
  },
  {
    id: 'academic-structure',
    label: 'Structure académique',
    path: '/app/pedagogy/academic-structure',
    icon: Layers,
    roles: ['SUPER_DIRECTOR', 'PLATFORM_OWNER', 'SCHOOL_OWNER', 'SCHOOL_ADMIN', 'director', 'admin'],
  },
  {
    id: 'subjects',
    label: 'Matières & programmes',
    path: '/app/pedagogy/subjects',
    icon: BookOpen,
    roles: ['SUPER_DIRECTOR', 'PLATFORM_OWNER', 'SCHOOL_OWNER', 'SCHOOL_ADMIN', 'director', 'admin'],
  },
  {
    id: 'teachers-academic',
    label: 'Enseignants académiques',
    path: '/app/pedagogy/teachers',
    icon: Users,
    roles: ['SUPER_DIRECTOR', 'PLATFORM_OWNER', 'SCHOOL_OWNER', 'SCHOOL_ADMIN', 'director', 'admin'],
  },
  {
    id: 'assignments',
    label: 'Affectations & charges',
    path: '/app/pedagogy/assignments',
    icon: ClipboardList,
    roles: ['SUPER_DIRECTOR', 'PLATFORM_OWNER', 'SCHOOL_OWNER', 'SCHOOL_ADMIN', 'director', 'admin'],
  },
  {
    id: 'class-diaries',
    label: 'Cahier de texte',
    path: '/app/pedagogy/class-diaries',
    icon: Book,
    roles: ['SUPER_DIRECTOR', 'PLATFORM_OWNER', 'SCHOOL_OWNER', 'SCHOOL_ADMIN', 'director', 'admin', 'TEACHER', 'TEACHER_RESP'],
  },
  {
    id: 'semainier',
    label: 'Cahier du semainier',
    path: '/app/pedagogy/semainier',
    icon: CalendarDays,
    roles: ['SUPER_DIRECTOR', 'PLATFORM_OWNER', 'SCHOOL_OWNER', 'SCHOOL_ADMIN', 'director', 'admin', 'TEACHER', 'TEACHER_RESP'],
  },
  {
    id: 'timetables',
    label: 'Emploi du temps',
    path: '/app/pedagogy/timetables',
    icon: Calendar,
    roles: ['SUPER_DIRECTOR', 'PLATFORM_OWNER', 'SCHOOL_OWNER', 'SCHOOL_ADMIN', 'director', 'admin', 'TEACHER', 'TEACHER_RESP'],
  },
  {
    id: 'pedagogical-production',
    label: 'Production pédagogique',
    path: '/app/pedagogy/production',
    icon: NotebookPen,
    roles: ['TEACHER', 'TEACHER_RESP'],
  },
  {
    id: 'materials',
    label: 'Matériel pédagogique',
    path: '/app/pedagogy/pedagogical-materials',
    icon: Package,
    roles: ['SUPER_DIRECTOR', 'PLATFORM_OWNER', 'SCHOOL_OWNER', 'SCHOOL_ADMIN', 'director', 'admin', 'TEACHER', 'TEACHER_RESP'],
  },
  {
    id: 'control',
    label: 'Contrôle direction',
    path: '/app/pedagogy/control',
    icon: ShieldCheck,
    roles: ['SUPER_DIRECTOR', 'PLATFORM_OWNER', 'SCHOOL_OWNER', 'SCHOOL_ADMIN', 'director', 'admin'],
  },
  {
    id: 'orion-pedagogy',
    label: 'Analytique ORION',
    path: '/app/pedagogy/orion',
    icon: BarChart3,
    roles: ['SUPER_DIRECTOR', 'PLATFORM_OWNER', 'SCHOOL_OWNER', 'SCHOOL_ADMIN', 'director', 'admin'],
  },
  {
    id: 'global-library',
    label: 'Bibliothèque virtuelle',
    path: '/app/pedagogy/global-library',
    icon: Book,
    roles: ['SUPER_DIRECTOR', 'PLATFORM_OWNER', 'SCHOOL_OWNER', 'SCHOOL_ADMIN', 'director', 'admin', 'TEACHER', 'TEACHER_RESP', 'PARENT', 'STUDENT'],
  },
  {
    id: 'teacher-tasks',
    label: 'Travaux & Suivi',
    path: '/app/pedagogy/tasks',
    icon: ClipboardList,
    roles: ['TEACHER', 'TEACHER_RESP', 'SUPER_DIRECTOR', 'director', 'admin'],
  },
  {
    id: 'sara-compose',
    label: 'Sara Compose (IA)',
    path: '/app/pedagogy/sara-compose',
    icon: Sparkles,
    roles: ['TEACHER', 'TEACHER_RESP', 'SUPER_DIRECTOR', 'director', 'admin'],
  },
] as const;

